"""Derive the U-series segment partition used by ``eprdating.series``.

Source: Adamiec G. & Aitken M. (1998) Dose-rate conversion factors: update.
Ancient TL 16(2): 37-50. https://doi.org/10.26034/la.atl.1998.292
(CC BY 4.0). Energies per disintegration (MeV) from Tables 2 and 3; dose
rates per ppm and abundances by weight from Table 5. Entries printed as
"<5x10^-4", "<5x10^-5" or "<0.005" are taken as 0, as in the paper's totals.
The full-series sums reproduce the paper's totals. Its printed "pre-Rn"
beta and gamma totals (0.906, 0.037 MeV) are slightly below the sums of the
listed isotopes (0.915, 0.039 MeV); the split here uses the isotope values.

Segments
--------
U-238 chain: U238 (238U, 234Th, 234mPa, 234Pa) | U234 | Th230 (230Th, 226Ra) | Rn222 (222Rn to 210Po)
U-235 chain: U235 (235U, 231Th) | Pa231 (231Pa to 207Tl)

Run from the repository root:  python tools/derive_u_series_partition.py
"""

import json
from pathlib import Path

# (alpha, beta, gamma) MeV per disintegration, Table 2 (U-238 series)
U238_TABLE = {
    "U-238": (4.19, 0.007, 0.0011),
    "Th-234": (0.0, 0.060, 0.0093),
    "Pa-234m": (0.0, 0.818, 0.0161),
    "Pa-234": (0.0, 0.001, 0.0023),
    "U-234": (4.68, 0.012, 0.0015),
    "Th-230": (4.58, 0.013, 0.0014),
    "Ra-226": (4.77, 0.0038, 0.0074),
    "Rn-222": (5.49, 0.0, 0.0004),
    "Po-218": (6.00, 0.0, 0.0),
    "Pb-214": (0.0, 0.294, 0.2521),
    "Bi-214": (0.0, 0.652, 1.4814),
    "Po-214": (7.68, 0.0, 0.0001),
    "Pb-210": (0.0, 0.033, 0.0047),
    "Bi-210": (0.0, 0.389, 0.0),
    "Po-210": (5.31, 0.0, 0.0),
}
U238_TOTAL = (42.7, 2.28, 1.78)
U238_SEGMENTS = {
    "U238": ["U-238", "Th-234", "Pa-234m", "Pa-234"],
    "U234": ["U-234"],
    "Th230": ["Th-230", "Ra-226"],
    "Rn222": ["Rn-222", "Po-218", "Pb-214", "Bi-214", "Po-214", "Pb-210", "Bi-210", "Po-210"],
}

# Table 3 (U-235 series)
U235_TABLE = {
    "U-235": (4.27, 0.037, 0.180),
    "Th-231": (0.0, 0.1506, 0.028),
    "Pa-231": (4.84, 0.032, 0.040),
    "Ac-227": (0.07, 0.0, 0.0),
    "Th-227": (5.70, 0.028, 0.108),
    "Fr-223": (0.0, 0.006, 0.001),
    "Ra-223": (5.67, 0.066, 0.137),
    "Rn-219": (6.63, 0.007, 0.058),
    "Po-215": (7.39, 0.0, 0.0),
    "Pb-211": (0.0, 0.455, 0.064),
    "Bi-211": (6.54, 0.001, 0.047),
    "Tl-207": (0.0, 0.494, 0.002),
}
U235_TOTAL = (41.1, 1.27, 0.665)
U235_SEGMENTS = {
    "U235": ["U-235", "Th-231"],
    "Pa231": ["Pa-231", "Ac-227", "Th-227", "Fr-223", "Ra-223", "Rn-219", "Po-215", "Pb-211", "Bi-211", "Tl-207"],
}

# Table 5: dose rate (Gy/ka per ppm of parent, full series) and weight abundance in natural U
DOSE_PER_PPM = {"U238": (2.685, 0.143, 0.112), "U235": (16.6, 0.515, 0.269)}
WEIGHT_ABUNDANCE = {"U238": 0.9929, "U235": 0.0071}
NAT_U_TOTAL = (2.78, 0.146, 0.113)

RADIATIONS = ("alpha", "beta", "gamma")


def segment_energies(table, segments, total):
    out = {}
    for seg, isotopes in segments.items():
        out[seg] = tuple(sum(table[i][r] for i in isotopes) for r in range(3))
    for r in range(3):
        s = sum(e[r] for e in out.values())
        assert abs(s - total[r]) / total[r] < 0.01, (segments, r, s, total[r])
    return out


def main():
    e238 = segment_energies(U238_TABLE, U238_SEGMENTS, U238_TOTAL)
    e235 = segment_energies(U235_TABLE, U235_SEGMENTS, U235_TOTAL)
    tot238 = [sum(e[r] for e in e238.values()) for r in range(3)]
    tot235 = [sum(e[r] for e in e235.values()) for r in range(3)]

    part = {}
    for r, rad in enumerate(RADIATIONS):
        d = {}
        for seg, e in e238.items():
            d[seg] = WEIGHT_ABUNDANCE["U238"] * DOSE_PER_PPM["U238"][r] * e[r] / tot238[r]
        for seg, e in e235.items():
            d[seg] = WEIGHT_ABUNDANCE["U235"] * DOSE_PER_PPM["U235"][r] * e[r] / tot235[r]
        nat_u = sum(d.values())
        assert abs(nat_u - NAT_U_TOTAL[r]) / NAT_U_TOTAL[r] < 0.01, (rad, nat_u)
        part[rad] = {k: round(v / nat_u, 6) for k, v in d.items()}
        # absorb rounding so fractions sum exactly to 1
        part[rad]["Rn222"] = round(1.0 - sum(v for k, v in part[rad].items() if k != "Rn222"), 6)

    doc = {
        "_comment": (
            "Fraction of the secular-equilibrium natural-U dose rate carried by each chain segment. "
            "U238 = 238U-234Th-234Pa; U234 = 234U; Th230 = 230Th-226Ra; Rn222 = 222Rn and daughters to 210Po; "
            "U235 = 235U-231Th; Pa231 = 231Pa and daughters. Generated by tools/derive_u_series_partition.py."
        ),
        "source": (
            "Adamiec G. & Aitken M. (1998) Dose-rate conversion factors: update. Ancient TL 16(2): 37-50, "
            "Tables 2, 3 and 5. doi:10.26034/la.atl.1998.292 (CC BY 4.0)"
        ),
        **part,
    }
    out = Path(__file__).resolve().parents[1] / "src/eprdating/data/u_series_partition.json"
    out.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    for rad in RADIATIONS:
        print(rad, part[rad])


if __name__ == "__main__":
    main()
